# Generated by Django 5.2.16 on 2026-07-19 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_populate_modules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Administrateur'), ('manager', 'Manager'), ('utilisateur', 'Utilisateur')], default='utilisateur', max_length=20, verbose_name='Rôle'),
        ),
    ]
