# Generated by Django 5.2.16 on 2026-07-19 22:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du produit')),
                ('categorie', models.CharField(choices=[('boisson', 'Boissons'), ('complement', 'Compléments alimentaires'), ('equipement', 'Équipements'), ('accessoire', 'Accessoires'), ('autre', 'Autre')], default='autre', max_length=20, verbose_name='Catégorie')),
                ('unite', models.CharField(choices=[('piece', 'Pièce'), ('carton', 'Carton'), ('litre', 'Litre'), ('kg', 'Kilogramme')], default='piece', max_length=20, verbose_name='Unité')),
                ('prix_achat', models.PositiveIntegerField(verbose_name="Prix d'achat (FCFA)")),
                ('prix_vente', models.PositiveIntegerField(blank=True, null=True, verbose_name='Prix de vente (FCFA)')),
                ('seuil_alerte', models.PositiveIntegerField(default=5, verbose_name="Seuil d'alerte (stock minimum)")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie')], max_length=10, verbose_name='Type de mouvement')),
                ('quantite', models.PositiveIntegerField(verbose_name='Quantité')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date du mouvement')),
                ('prix_unitaire', models.PositiveIntegerField(verbose_name='Prix unitaire (FCFA)')),
                ('motif', models.CharField(blank=True, choices=[('vente', 'Vente au client'), ('perte', 'Casse / Perte'), ('usage_interne', 'Usage interne')], max_length=20, verbose_name='Motif de sortie')),
                ('date_peremption', models.DateField(blank=True, null=True, verbose_name='Date de péremption')),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock_enregistres', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements', to='stock.fournisseur', verbose_name='Fournisseur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='stock.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-date'],
            },
        ),
    ]
