# Generated by Django 5.2.16 on 2026-07-21 11:34, puis réécrite à la main pour
# convertir en toute sécurité les produits existants (categorie passe de
# CharField figé à ForeignKey vers la nouvelle table configurable
# CategorieProduit), sur le même modèle que la conversion de TypePrestation.

import django.db.models.deletion
from django.db import migrations, models

CATEGORIES_SEED = [
    {'cle': 'boisson', 'nom': 'Boissons'},
    {'cle': 'complement', 'nom': 'Compléments alimentaires'},
    {'cle': 'equipement', 'nom': 'Équipements'},
    {'cle': 'accessoire', 'nom': 'Accessoires'},
    {'cle': 'autre', 'nom': 'Autre'},
]


def seed_categories(apps, schema_editor):
    CategorieProduit = apps.get_model('stock', 'CategorieProduit')
    for data in CATEGORIES_SEED:
        CategorieProduit.objects.get_or_create(cle=data['cle'], defaults=data)


def convert_produits(apps, schema_editor):
    Produit = apps.get_model('stock', 'Produit')
    CategorieProduit = apps.get_model('stock', 'CategorieProduit')
    mapping = {c.cle: c.id for c in CategorieProduit.objects.all()}
    for produit in Produit.objects.all():
        cat_id = mapping.get(produit.categorie_ancienne)
        if cat_id:
            produit.categorie_fk_id = cat_id
            produit.save(update_fields=['categorie_fk'])


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.SlugField(blank=True, null=True, unique=True, verbose_name='Clé technique')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Catégorie de produit',
                'verbose_name_plural': 'Catégories de produit',
                'ordering': ['nom'],
            },
        ),
        migrations.RunPython(seed_categories, migrations.RunPython.noop),

        migrations.RenameField(model_name='produit', old_name='categorie', new_name='categorie_ancienne'),
        migrations.AddField(
            model_name='produit',
            name='categorie_fk',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT,
                related_name='produits_tmp', to='stock.categorieproduit',
            ),
        ),

        migrations.RunPython(convert_produits, migrations.RunPython.noop),

        migrations.RemoveField(model_name='produit', name='categorie_ancienne'),
        migrations.RenameField(model_name='produit', old_name='categorie_fk', new_name='categorie'),
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name='produits',
                to='stock.categorieproduit', verbose_name='Catégorie',
            ),
        ),
    ]
