# Generated by Django 5.2.16 on 2026-07-22 05:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def rattacher_ventes_existantes(apps, schema_editor):
    """Crée un objet Vente pour chaque ancienne ligne de vente isolée (avant
    l'introduction du panier multi-produits), pour que l'historique reste
    cohérent avec le nouveau modèle."""
    MouvementStock = apps.get_model('stock', 'MouvementStock')
    Vente = apps.get_model('stock', 'Vente')

    for mouvement in MouvementStock.objects.filter(type_mouvement='sortie', motif='vente', vente__isnull=True):
        vente = Vente.objects.create(
            date=mouvement.date,
            mode_paiement=mouvement.mode_paiement,
            operateur_mobile_money=mouvement.operateur_mobile_money,
            enregistre_par=mouvement.enregistre_par,
        )
        mouvement.vente = vente
        mouvement.save(update_fields=['vente'])


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_mouvementstock_mode_paiement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('mobile_money', 'Mobile Money'), ('autre', 'Autre')], default='especes', max_length=20, verbose_name='Mode de paiement')),
                ('operateur_mobile_money', models.CharField(blank=True, choices=[('wave', 'Wave'), ('mtn', 'MTN'), ('moov', 'Moov'), ('orange', 'Orange')], max_length=20, verbose_name='Opérateur Mobile Money')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de la vente')),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes_enregistrees', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
            ],
            options={
                'verbose_name': 'Vente',
                'verbose_name_plural': 'Ventes',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='vente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='stock.vente', verbose_name='Vente (panier)'),
        ),
        migrations.RunPython(rattacher_ventes_existantes, migrations.RunPython.noop),
    ]
