# Generated by Django 5.2.16 on 2026-08-01 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_vente_mouvementstock_vente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementstock',
            name='motif',
            field=models.CharField(blank=True, choices=[('achat', 'Achat fournisseur'), ('stock_initial', 'Stock initial / Inventaire de départ'), ('vente', 'Vente au client'), ('perte', 'Casse / Perte'), ('usage_interne', 'Usage interne')], max_length=20, verbose_name='Motif'),
        ),
    ]
