# Generated by Django 5.2.16 on 2026-08-22 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_alter_mouvementstock_motif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementstock',
            name='mode_paiement',
            field=models.CharField(choices=[('especes', 'Espèces'), ('mobile_money', 'Mobile Money'), ('cheque', 'Chèque')], default='especes', max_length=20, verbose_name='Mode de paiement'),
        ),
        migrations.AlterField(
            model_name='vente',
            name='mode_paiement',
            field=models.CharField(choices=[('especes', 'Espèces'), ('mobile_money', 'Mobile Money'), ('cheque', 'Chèque')], default='especes', max_length=20, verbose_name='Mode de paiement'),
        ),
    ]
