# Generated by Django 5.2.16 on 2026-07-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etablissement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='solde_initial_caisse',
            field=models.PositiveIntegerField(default=0, help_text='Montant déjà en caisse au moment où vous commencez à utiliser le logiciel.', verbose_name='Solde de caisse initial (FCFA)'),
        ),
    ]
