# Generated by Django 5.2.16 on 2026-07-29 15:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etablissement', '0002_etablissement_solde_initial_caisse'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='couleur_principale',
            field=models.CharField(default='#386745', help_text='Utilisée pour la navigation, les boutons et les en-têtes de document (PDF).', max_length=7, validators=[django.core.validators.RegexValidator(message='Couleur au format hexadécimal, ex : #386745', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Couleur principale'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='couleur_secondaire',
            field=models.CharField(default='#FDF7E5', help_text='Utilisée pour le texte sur fond de couleur principale (ex : slogan).', max_length=7, validators=[django.core.validators.RegexValidator(message='Couleur au format hexadécimal, ex : #386745', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Couleur secondaire'),
        ),
    ]
