# Generated by Django 5.2.16 on 2026-07-29 15:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etablissement', '0003_etablissement_couleur_principale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='couleur_accent',
            field=models.CharField(default='#F46722', help_text='Utilisée au survol des menus et des boutons.', max_length=7, validators=[django.core.validators.RegexValidator(message='Couleur au format hexadécimal, ex : #386745', regex='^#[0-9A-Fa-f]{6}$')], verbose_name="Couleur d'accent (survol)"),
        ),
    ]
