# Generated by Django 5.2.16 on 2026-07-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etablissement', '0005_etablissement_indicatif_pays_defaut'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='message_partage_carte',
            field=models.TextField(default="Bonjour {client}, voici votre carte de membre {etablissement} ({type_abonnement}, valable jusqu'au {date_expiration}) :\n{lien_carte}", help_text='Variables disponibles : {client}, {etablissement}, {type_abonnement}, {date_expiration}, {lien_carte}.', verbose_name='Message de partage de la carte de membre'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='message_relance',
            field=models.TextField(default="Bonjour {client}, votre {type_abonnement} chez {etablissement} expire le {date_expiration} ({jours_restants} jour(s) restant(s)). Pensez à le renouveler pour ne pas perdre l'accès à la salle !", help_text='Variables disponibles : {client}, {etablissement}, {type_abonnement}, {date_expiration}, {jours_restants}.', verbose_name='Message de relance avant expiration'),
        ),
    ]
