"""Indicatifs téléphoniques internationaux (pays + indicatif), utilisés pour
construire un numéro complet lors du partage WhatsApp (cf. Etablissement et
Client.indicatif_pays) — le champ `telephone` reste inchangé (recherche/
unicité des clients), l'indicatif est stocké à part."""

INDICATIFS_PAYS = [
    ('+93', 'Afghanistan'),
    ('+27', 'Afrique du Sud'),
    ('+355', 'Albanie'),
    ('+213', 'Algérie'),
    ('+49', 'Allemagne'),
    ('+376', 'Andorre'),
    ('+244', 'Angola'),
    ('+1264', 'Anguilla'),
    ('+1268', 'Antigua-et-Barbuda'),
    ('+966', 'Arabie saoudite'),
    ('+54', 'Argentine'),
    ('+374', 'Arménie'),
    ('+297', 'Aruba'),
    ('+61', 'Australie'),
    ('+43', 'Autriche'),
    ('+994', 'Azerbaïdjan'),
    ('+1242', 'Bahamas'),
    ('+973', 'Bahreïn'),
    ('+880', 'Bangladesh'),
    ('+1246', 'Barbade'),
    ('+32', 'Belgique'),
    ('+501', 'Belize'),
    ('+229', 'Bénin'),
    ('+975', 'Bhoutan'),
    ('+375', 'Biélorussie'),
    ('+95', 'Birmanie (Myanmar)'),
    ('+591', 'Bolivie'),
    ('+387', 'Bosnie-Herzégovine'),
    ('+267', 'Botswana'),
    ('+55', 'Brésil'),
    ('+673', 'Brunei'),
    ('+359', 'Bulgarie'),
    ('+226', 'Burkina Faso'),
    ('+257', 'Burundi'),
    ('+855', 'Cambodge'),
    ('+237', 'Cameroun'),
    ('+1', 'Canada'),
    ('+238', 'Cap-Vert'),
    ('+236', 'République centrafricaine'),
    ('+56', 'Chili'),
    ('+86', 'Chine'),
    ('+357', 'Chypre'),
    ('+57', 'Colombie'),
    ('+269', 'Comores'),
    ('+242', 'Congo (Brazzaville)'),
    ('+243', 'Congo (RD - Kinshasa)'),
    ('+850', 'Corée du Nord'),
    ('+82', 'Corée du Sud'),
    ('+506', 'Costa Rica'),
    ('+225', "Côte d'Ivoire"),
    ('+385', 'Croatie'),
    ('+53', 'Cuba'),
    ('+45', 'Danemark'),
    ('+253', 'Djibouti'),
    ('+1767', 'Dominique'),
    ('+20', 'Égypte'),
    ('+971', 'Émirats arabes unis'),
    ('+593', 'Équateur'),
    ('+291', 'Érythrée'),
    ('+34', 'Espagne'),
    ('+372', 'Estonie'),
    ('+268', 'Eswatini (Swaziland)'),
    ('+1', 'États-Unis'),
    ('+251', 'Éthiopie'),
    ('+679', 'Fidji'),
    ('+358', 'Finlande'),
    ('+33', 'France'),
    ('+241', 'Gabon'),
    ('+220', 'Gambie'),
    ('+995', 'Géorgie'),
    ('+233', 'Ghana'),
    ('+30', 'Grèce'),
    ('+1473', 'Grenade'),
    ('+502', 'Guatemala'),
    ('+224', 'Guinée'),
    ('+245', 'Guinée-Bissau'),
    ('+240', 'Guinée équatoriale'),
    ('+592', 'Guyana'),
    ('+509', 'Haïti'),
    ('+504', 'Honduras'),
    ('+36', 'Hongrie'),
    ('+682', 'Îles Cook'),
    ('+692', 'Îles Marshall'),
    ('+677', 'Îles Salomon'),
    ('+91', 'Inde'),
    ('+62', 'Indonésie'),
    ('+964', 'Irak'),
    ('+98', 'Iran'),
    ('+353', 'Irlande'),
    ('+354', 'Islande'),
    ('+972', 'Israël'),
    ('+39', 'Italie'),
    ('+1876', 'Jamaïque'),
    ('+81', 'Japon'),
    ('+962', 'Jordanie'),
    ('+7', 'Kazakhstan'),
    ('+254', 'Kenya'),
    ('+996', 'Kirghizistan'),
    ('+686', 'Kiribati'),
    ('+965', 'Koweït'),
    ('+856', 'Laos'),
    ('+266', 'Lesotho'),
    ('+371', 'Lettonie'),
    ('+961', 'Liban'),
    ('+231', 'Liberia'),
    ('+218', 'Libye'),
    ('+423', 'Liechtenstein'),
    ('+370', 'Lituanie'),
    ('+352', 'Luxembourg'),
    ('+389', 'Macédoine du Nord'),
    ('+261', 'Madagascar'),
    ('+60', 'Malaisie'),
    ('+265', 'Malawi'),
    ('+960', 'Maldives'),
    ('+223', 'Mali'),
    ('+356', 'Malte'),
    ('+212', 'Maroc'),
    ('+230', 'Maurice'),
    ('+222', 'Mauritanie'),
    ('+52', 'Mexique'),
    ('+691', 'Micronésie'),
    ('+373', 'Moldavie'),
    ('+377', 'Monaco'),
    ('+976', 'Mongolie'),
    ('+382', 'Monténégro'),
    ('+258', 'Mozambique'),
    ('+264', 'Namibie'),
    ('+674', 'Nauru'),
    ('+977', 'Népal'),
    ('+505', 'Nicaragua'),
    ('+227', 'Niger'),
    ('+234', 'Nigeria'),
    ('+683', 'Niue'),
    ('+47', 'Norvège'),
    ('+64', 'Nouvelle-Zélande'),
    ('+968', 'Oman'),
    ('+256', 'Ouganda'),
    ('+998', 'Ouzbékistan'),
    ('+92', 'Pakistan'),
    ('+680', 'Palaos'),
    ('+970', 'Palestine'),
    ('+507', 'Panama'),
    ('+675', 'Papouasie-Nouvelle-Guinée'),
    ('+595', 'Paraguay'),
    ('+31', 'Pays-Bas'),
    ('+51', 'Pérou'),
    ('+63', 'Philippines'),
    ('+48', 'Pologne'),
    ('+351', 'Portugal'),
    ('+974', 'Qatar'),
    ('+1809', 'République dominicaine'),
    ('+420', 'République tchèque (Tchéquie)'),
    ('+40', 'Roumanie'),
    ('+44', 'Royaume-Uni'),
    ('+7', 'Russie'),
    ('+250', 'Rwanda'),
    ('+1869', 'Saint-Christophe-et-Niévès'),
    ('+378', 'Saint-Marin'),
    ('+1784', 'Saint-Vincent-et-les-Grenadines'),
    ('+1758', 'Sainte-Lucie'),
    ('+503', 'Salvador'),
    ('+685', 'Samoa'),
    ('+239', 'Sao Tomé-et-Principe'),
    ('+221', 'Sénégal'),
    ('+381', 'Serbie'),
    ('+248', 'Seychelles'),
    ('+232', 'Sierra Leone'),
    ('+65', 'Singapour'),
    ('+421', 'Slovaquie'),
    ('+386', 'Slovénie'),
    ('+252', 'Somalie'),
    ('+249', 'Soudan'),
    ('+211', 'Soudan du Sud'),
    ('+94', 'Sri Lanka'),
    ('+46', 'Suède'),
    ('+41', 'Suisse'),
    ('+597', 'Suriname'),
    ('+963', 'Syrie'),
    ('+992', 'Tadjikistan'),
    ('+255', 'Tanzanie'),
    ('+235', 'Tchad'),
    ('+66', 'Thaïlande'),
    ('+670', 'Timor oriental'),
    ('+228', 'Togo'),
    ('+676', 'Tonga'),
    ('+1868', 'Trinité-et-Tobago'),
    ('+216', 'Tunisie'),
    ('+993', 'Turkménistan'),
    ('+90', 'Turquie'),
    ('+688', 'Tuvalu'),
    ('+380', 'Ukraine'),
    ('+598', 'Uruguay'),
    ('+678', 'Vanuatu'),
    ('+379', 'Vatican'),
    ('+58', 'Venezuela'),
    ('+84', 'Vietnam'),
    ('+967', 'Yémen'),
    ('+260', 'Zambie'),
    ('+263', 'Zimbabwe'),
]

# Libellé affiché dans les listes déroulantes : "Pays (+indicatif)".
CHOIX_INDICATIFS_PAYS = [(code, f"{pays} ({code})") for code, pays in INDICATIFS_PAYS]
