# Generated by Django 5.2.16 on 2026-07-19 17:13

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_typeprestation_alter_seance_type_prestation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeAbonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.SlugField(blank=True, null=True, unique=True, verbose_name='Clé technique')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prix', models.PositiveIntegerField(verbose_name='Prix (FCFA)')),
                ('duree_jours', models.PositiveIntegerField(default=30, verbose_name='Durée (jours)')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': "Type d'abonnement",
                'verbose_name_plural': "Types d'abonnement",
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('mobile_money', 'Mobile Money'), ('autre', 'Autre')], default='especes', max_length=20, verbose_name='Mode de paiement')),
                ('operateur_mobile_money', models.CharField(blank=True, choices=[('wave', 'Wave'), ('mtn', 'MTN'), ('moov', 'Moov'), ('orange', 'Orange')], max_length=20, verbose_name='Opérateur Mobile Money')),
                ('statut_paiement', models.CharField(choices=[('paye', 'Payé'), ('en_attente', 'En attente')], default='en_attente', max_length=20, verbose_name='Statut du paiement')),
                ('date_souscription', models.DateTimeField(auto_now_add=True, verbose_name='Date de souscription')),
                ('date_debut', models.DateField(default=datetime.date.today, verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name="Date d'expiration")),
                ('montant', models.PositiveIntegerField(verbose_name='Montant')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to='clients.client', verbose_name='Client')),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abonnements_enregistres', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('type_abonnement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonnements', to='abonnements.typeabonnement', verbose_name="Type d'abonnement")),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
                'ordering': ['-date_debut'],
            },
        ),
    ]
