# Generated by Django 5.2.16 on 2026-07-19 17:55, puis réécrite à la main pour
# convertir en toute sécurité les abonnements existants (le paiement, autrefois
# un champ figé sur l'abonnement, devient un historique de versements).

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def convert_paiements(apps, schema_editor):
    """Les abonnements déjà marqués 'payé' deviennent un versement intégral ;
    ceux 'en_attente' ne génèrent aucun versement (rien n'a été reçu)."""
    Abonnement = apps.get_model('abonnements', 'Abonnement')
    PaiementAbonnement = apps.get_model('abonnements', 'PaiementAbonnement')
    for abonnement in Abonnement.objects.all():
        if abonnement.statut_paiement == 'paye':
            PaiementAbonnement.objects.create(
                abonnement=abonnement,
                montant=abonnement.montant,
                date=abonnement.date_souscription,
                mode_paiement=abonnement.mode_paiement,
                operateur_mobile_money=abonnement.operateur_mobile_money,
                enregistre_par=abonnement.enregistre_par,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('abonnements', '0002_populate_types_abonnement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementAbonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('mobile_money', 'Mobile Money'), ('autre', 'Autre')], default='especes', max_length=20, verbose_name='Mode de paiement')),
                ('operateur_mobile_money', models.CharField(blank=True, choices=[('wave', 'Wave'), ('mtn', 'MTN'), ('moov', 'Moov'), ('orange', 'Orange')], max_length=20, verbose_name='Opérateur Mobile Money')),
                ('montant', models.PositiveIntegerField(verbose_name='Montant versé')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date du versement')),
                ('abonnement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='abonnements.abonnement', verbose_name='Abonnement')),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_abonnements_enregistres', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
            ],
            options={
                'verbose_name': "Paiement d'abonnement",
                'verbose_name_plural': "Paiements d'abonnement",
                'ordering': ['date'],
            },
        ),

        migrations.RunPython(convert_paiements, migrations.RunPython.noop),

        migrations.RemoveField(
            model_name='abonnement',
            name='mode_paiement',
        ),
        migrations.RemoveField(
            model_name='abonnement',
            name='operateur_mobile_money',
        ),
        migrations.RemoveField(
            model_name='abonnement',
            name='statut_paiement',
        ),
    ]
