# Generated by Django 5.2.16 on 2026-07-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnements', '0003_remove_abonnement_mode_paiement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnement',
            name='date_relance',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de la relance'),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='relance_effectuee',
            field=models.BooleanField(default=False, verbose_name='Client contacté'),
        ),
    ]
