# Generated by Django 5.2.16 on 2026-07-23 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abonnements', '0004_abonnement_date_relance_abonnement_relance_effectuee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiementabonnement',
            name='abonnement',
        ),
        migrations.RemoveField(
            model_name='paiementabonnement',
            name='enregistre_par',
        ),
    ]
