# Generated by Django 5.2.16 on 2026-07-23 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abonnements', '0005_remove_paiementabonnement_abonnement_and_more'),
        ('budget', '0003_remove_operationbudget_paiement_abonnement_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaiementAbonnement',
        ),
    ]
