# Generated by Django 5.2.16 on 2026-07-29 15:51
# Ajustée à la main : ajout en 2 temps pour peupler les abonnements
# existants avant d'imposer la contrainte unique (SQLite évalue le default
# une seule fois pour tout le batch d'ALTER TABLE, pas par ligne).

import uuid

from django.db import migrations, models


def generer_public_id(apps, schema_editor):
    Abonnement = apps.get_model('abonnements', 'Abonnement')
    for abonnement in Abonnement.objects.all():
        abonnement.public_id = uuid.uuid4()
        abonnement.save(update_fields=['public_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('abonnements', '0006_delete_paiementabonnement'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnement',
            name='public_id',
            field=models.UUIDField(null=True, editable=False, db_index=True,
                                    help_text="Utilisé dans l'URL de vérification de la carte de membre (QR code), pour ne pas exposer l'ID interne.",
                                    verbose_name='Identifiant public'),
        ),
        migrations.RunPython(generer_public_id, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='abonnement',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, db_index=True,
                                    help_text="Utilisé dans l'URL de vérification de la carte de membre (QR code), pour ne pas exposer l'ID interne.",
                                    verbose_name='Identifiant public'),
        ),
    ]
