# Generated by Django 5.2.16 on 2026-08-01 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnements', '0007_abonnement_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnement',
            name='mode_paiement',
            field=models.CharField(choices=[('especes', 'Espèces'), ('mobile_money', 'Mobile Money'), ('autre', 'Autre')], default='especes', max_length=20, verbose_name='Mode de paiement'),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='operateur_mobile_money',
            field=models.CharField(blank=True, choices=[('wave', 'Wave'), ('mtn', 'MTN'), ('moov', 'Moov'), ('orange', 'Orange')], max_length=20, verbose_name='Opérateur Mobile Money'),
        ),
    ]
