# Generated by Django 5.2.16 on 2026-07-19 06:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('telephone', models.CharField(max_length=20, unique=True, verbose_name='Téléphone')),
                ('nom_complet', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('objectif', models.CharField(blank=True, choices=[('perte_poids', 'Perte de poids'), ('prise_masse', 'Prise de masse musculaire'), ('remise_forme', 'Remise en forme / Bien-être'), ('preparation_sportive', 'Préparation sportive')], max_length=30, verbose_name='Objectif sportif')),
                ('contact_urgence_nom', models.CharField(blank=True, max_length=200, verbose_name="Contact d'urgence — Nom")),
                ('contact_urgence_telephone', models.CharField(blank=True, max_length=20, verbose_name="Contact d'urgence — Téléphone")),
                ('antecedents_medicaux', models.TextField(blank=True, verbose_name='Antécédents médicaux / contre-indications')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['nom_complet'],
            },
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('type_prestation', models.CharField(choices=[('simple', 'Séance simple'), ('tapis', 'Séance + tapis de course'), ('vip', 'Séance VIP (toutes machines)')], max_length=20, verbose_name='Type de prestation')),
                ('montant', models.PositiveIntegerField(verbose_name='Montant')),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('mobile_money', 'Mobile Money'), ('autre', 'Autre')], default='especes', max_length=20, verbose_name='Mode de paiement')),
                ('statut_paiement', models.CharField(choices=[('paye', 'Payé'), ('en_attente', 'En attente')], default='en_attente', max_length=20, verbose_name='Statut du paiement')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='clients.client', verbose_name='Client')),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seances_enregistrees', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
            ],
            options={
                'verbose_name': 'Séance',
                'verbose_name_plural': 'Séances',
                'ordering': ['-date'],
            },
        ),
    ]
