# Generated by Django 5.2.16 on 2026-07-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='operateur_mobile_money',
            field=models.CharField(blank=True, choices=[('wave', 'Wave'), ('mtn', 'MTN'), ('moov', 'Moov'), ('orange', 'Orange')], max_length=20, verbose_name='Opérateur Mobile Money'),
        ),
    ]
