# Generated by Django 5.2.16 on 2026-07-19 06:43, puis réécrite à la main pour
# convertir en toute sécurité les séances existantes (type_prestation passe de
# CharField figé à ForeignKey vers la nouvelle table configurable TypePrestation).

import django.db.models.deletion
from django.db import migrations, models

TYPES_SEED = [
    {'cle': 'simple', 'nom': 'Séance simple', 'prix': 1000, 'ordre': 1},
    {'cle': 'tapis', 'nom': 'Séance + tapis de course', 'prix': 2000, 'ordre': 2},
    {'cle': 'vip', 'nom': 'Séance VIP (toutes machines)', 'prix': 5000, 'ordre': 3},
]


def seed_types(apps, schema_editor):
    TypePrestation = apps.get_model('clients', 'TypePrestation')
    for data in TYPES_SEED:
        TypePrestation.objects.get_or_create(cle=data['cle'], defaults=data)


def convert_seances(apps, schema_editor):
    Seance = apps.get_model('clients', 'Seance')
    TypePrestation = apps.get_model('clients', 'TypePrestation')
    mapping = {tp.cle: tp.id for tp in TypePrestation.objects.all()}
    for seance in Seance.objects.all():
        tp_id = mapping.get(seance.type_prestation_ancien)
        if tp_id:
            seance.type_prestation_fk_id = tp_id
            seance.save(update_fields=['type_prestation_fk'])


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_seance_operateur_mobile_money'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypePrestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.SlugField(blank=True, null=True, unique=True, verbose_name='Clé technique')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prix', models.PositiveIntegerField(verbose_name='Prix (FCFA)')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Type de prestation',
                'verbose_name_plural': 'Types de prestation',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.RunPython(seed_types, migrations.RunPython.noop),

        # Renommer l'ancien champ texte pour libérer le nom 'type_prestation'
        migrations.RenameField(model_name='seance', old_name='type_prestation', new_name='type_prestation_ancien'),

        # Ajouter le nouveau champ FK (nullable pour la conversion des données)
        migrations.AddField(
            model_name='seance',
            name='type_prestation_fk',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT,
                related_name='seances_tmp', to='clients.typeprestation',
            ),
        ),

        # Convertir chaque séance existante : ancienne valeur texte -> FK
        migrations.RunPython(convert_seances, migrations.RunPython.noop),

        # Supprimer l'ancien champ texte, puis finaliser le nouveau champ FK
        migrations.RemoveField(model_name='seance', name='type_prestation_ancien'),
        migrations.RenameField(model_name='seance', old_name='type_prestation_fk', new_name='type_prestation'),
        migrations.AlterField(
            model_name='seance',
            name='type_prestation',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name='seances',
                to='clients.typeprestation', verbose_name='Type de prestation',
            ),
        ),
    ]
