# Generated by Django 5.2.16 on 2026-07-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_typeprestation_alter_seance_type_prestation'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='bassin',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Tour de bassin (cm)'),
        ),
        migrations.AddField(
            model_name='client',
            name='photo_cni',
            field=models.ImageField(blank=True, null=True, upload_to='clients/cni/', verbose_name="Photo de la pièce d'identité (CNI)"),
        ),
        migrations.AddField(
            model_name='client',
            name='poids',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Poids (kg)'),
        ),
        migrations.AddField(
            model_name='client',
            name='taille',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Taille (cm)'),
        ),
    ]
