# Generated by Django 5.2.16 on 2026-07-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_bassin_client_photo_cni_client_poids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeprestation',
            name='duree_minutes',
            field=models.PositiveIntegerField(default=30, verbose_name='Durée (minutes)'),
        ),
    ]
