# Generated by Django 5.2.16 on 2026-07-31 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_objectifsportif'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quartier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Quartier',
                'verbose_name_plural': 'Quartiers',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='adresse',
            field=models.TextField(blank=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_urgence_nom',
            field=models.CharField(blank=True, max_length=200, verbose_name="Personne d'urgence"),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_urgence_telephone',
            field=models.CharField(blank=True, max_length=20, verbose_name="Contact d'urgence"),
        ),
        migrations.AddField(
            model_name='client',
            name='quartier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='clients.quartier', verbose_name='Quartier / zone'),
        ),
    ]
