# Generated by Django 5.2.16 on 2026-08-22 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationFNE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name="Identifiant de l'objet")),
                ('statut', models.CharField(choices=[('succes', 'Certifié'), ('echec', 'Échec'), ('desactive', 'Non tenté (FNE désactivée)')], max_length=20, verbose_name='Statut')),
                ('payload_envoye', models.JSONField(verbose_name='Données envoyées')),
                ('reference_fne', models.CharField(blank=True, max_length=100, verbose_name='Référence FNE')),
                ('token_verification', models.URLField(blank=True, help_text='URL à encoder en QR code sur le document imprimé.', max_length=500, verbose_name='Lien de vérification')),
                ('balance_sticker', models.IntegerField(blank=True, null=True, verbose_name='Solde de stickers restants')),
                ('erreur_code', models.CharField(blank=True, max_length=20, verbose_name="Code d'erreur")),
                ('erreur_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('date_tentative', models.DateTimeField(auto_now_add=True, verbose_name='Date de la tentative')),
                ('date_derniere_maj', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name="Type d'objet")),
            ],
            options={
                'verbose_name': 'Certification FNE',
                'verbose_name_plural': 'Certifications FNE',
                'ordering': ['-date_tentative'],
            },
        ),
    ]
