# Generated by Django 5.2.16 on 2026-07-20 07:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abonnements', '0003_remove_abonnement_mode_paiement_and_more'),
        ('clients', '0003_typeprestation_alter_seance_type_prestation'),
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Catégorie de charge',
                'verbose_name_plural': 'Catégories de charge',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='OperationBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('mobile_money', 'Mobile Money'), ('autre', 'Autre')], default='especes', max_length=20, verbose_name='Mode de paiement')),
                ('operateur_mobile_money', models.CharField(blank=True, choices=[('wave', 'Wave'), ('mtn', 'MTN'), ('moov', 'Moov'), ('orange', 'Orange')], max_length=20, verbose_name='Opérateur Mobile Money')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date de l'opération")),
                ('type_operation', models.CharField(choices=[('entree', "Entrée d'argent"), ('sortie', "Sortie d'argent")], max_length=10, verbose_name="Type d'opération")),
                ('categorie', models.CharField(choices=[('recette_seance', 'Recette séance'), ('recette_abonnement', 'Recette abonnement'), ('achat_produit', 'Achat produit'), ('vente_produit', 'Vente produit'), ('charge', 'Charge'), ('salaire', 'Salaire'), ('autre', 'Autre')], max_length=30, verbose_name='Catégorie')),
                ('montant', models.PositiveIntegerField(verbose_name='Montant')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('categorie_charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='budget.categoriecharge', verbose_name='Catégorie de charge')),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_budget_enregistrees', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('mouvement_stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_budget', to='stock.mouvementstock')),
                ('paiement_abonnement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_budget', to='abonnements.paiementabonnement')),
                ('seance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_budget', to='clients.seance')),
            ],
            options={
                'verbose_name': 'Opération budgétaire',
                'verbose_name_plural': 'Opérations budgétaires',
                'ordering': ['-date'],
            },
        ),
    ]
