# Generated by Django 5.2.16 on 2026-07-22 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
        ('stock', '0004_vente_mouvementstock_vente'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationbudget',
            name='vente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_budget', to='stock.vente'),
        ),
    ]
