# Generated by Django 5.2.16 on 2026-07-23 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnements', '0005_remove_paiementabonnement_abonnement_and_more'),
        ('budget', '0002_operationbudget_vente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationbudget',
            name='paiement_abonnement',
        ),
        migrations.AddField(
            model_name='operationbudget',
            name='abonnement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_budget', to='abonnements.abonnement'),
        ),
    ]
