# Generated by Django 5.2.16 on 2026-07-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_remove_operationbudget_paiement_abonnement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationbudget',
            name='categorie',
            field=models.CharField(choices=[('recette_seance', 'Recette séance'), ('recette_abonnement', 'Recette abonnement'), ('achat_produit', 'Achat produit'), ('vente_produit', 'Vente produit'), ('perte_produit', 'Perte / Usage interne produit'), ('charge', 'Charge'), ('salaire', 'Salaire'), ('autre', 'Autre')], max_length=30, verbose_name='Catégorie'),
        ),
    ]
