# Generated by Django 5.2.16 on 2026-09-23 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_alter_operationbudget_mode_paiement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='operationbudget',
            name='annulee',
            field=models.BooleanField(default=False, verbose_name='Annulée'),
        ),
        migrations.AddField(
            model_name='operationbudget',
            name='annulee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_budget_annulees', to=settings.AUTH_USER_MODEL, verbose_name='Annulée par'),
        ),
        migrations.AddField(
            model_name='operationbudget',
            name='date_annulation',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'annulation"),
        ),
    ]
